// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnizxg9hFDdSdPJshVoJBNaMM33kIbsCE',
    appId: '1:826955874521:android:1299c0cf9658155a06bec8',
    messagingSenderId: '826955874521',
    projectId: 'chatapp-5f77a',
    storageBucket: 'chatapp-5f77a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwp2wPMi9CAd4Zb3QwbnM3LShaIDjHTIg',
    appId: '1:826955874521:ios:4eeda6abe580abda06bec8',
    messagingSenderId: '826955874521',
    projectId: 'chatapp-5f77a',
    storageBucket: 'chatapp-5f77a.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeOl_oXavQJag6UExAw1cI6mX4NRLfXSw',
    appId: '1:826955874521:web:6cd20ee2e24e9a0e06bec8',
    messagingSenderId: '826955874521',
    projectId: 'chatapp-5f77a',
    authDomain: 'chatapp-5f77a.firebaseapp.com',
    storageBucket: 'chatapp-5f77a.firebasestorage.app',
    measurementId: 'G-Y2LTMXJQTN',
  );

}